#!/usr/bin/env zsh
ln -sf ~/dotfiles/tmux.conf ~/.tmux.conf
ln -sf ~/dotfiles/tmate.conf ~/.tmate.conf
ln -sf ~/dotfiles/zshrc ~/.zshrc
ln -sf ~/dotfiles/zprofile ~/.zprofile
ln -sf ~/dotfiles/aliases ~/.aliases
ln -sf ~/dotfiles/functions ~/.functions
ln -sf ~/dotfiles/gitconfig ~/.gitconfig
ln -sf ~/dotfiles/gitignore_global ~/.gitignore_global
ln -sf ~/dotfiles/vimrc ~/.vimrc
ln -sf ~/dotfiles/alacritty.yml ~/.alacritty.yml
ln -sf ~/dotfiles/config ~/.config
mkdir -p ~/.ignores
# ~/.ignores/exports is generated by setup_scripts/refresh_secrets.sh (plaintext, gitignored)
# op_exports is the 1Password reference template (committed)
ln -sf ~/dotfiles/config/hammerspoon ~/.hammerspoon
ln -sf ~/dotfiles/config/claude/CLAUDE.md ~/.claude/CLAUDE.md
ln -sf ~/dotfiles/config/claude/settings.json ~/.claude/settings.json
ln -sf ~/dotfiles/config/claude/settings.local.json ~/.claude/settings.local.json
# Claude Code directories — warn if real dir exists (may have unsynced content)
for dir in agents commands hooks; do
  target="$HOME/.claude/$dir"
  if [ -L "$target" ]; then
    rm "$target"
  elif [ -d "$target" ]; then
    echo "⚠️  ~/.claude/$dir is a real directory — back it up or merge before re-running."
    continue
  fi
  ln -sf ~/dotfiles/config/claude/$dir "$target"
done
